### ISSUE TITLE
Set up `prettier` + `husky` + `lint-staged`

### ISSUE THREAD

**Issue by with-heart** [Developer-DAO/school-of-code#11]

**Comment by with-heart** [comment]
Here's a reference PR if someone wants to attempt to do this: https://github.com/Developer-DAO/discord-server-info/pull/9

The [`lint-staged` docs](https://github.com/okonet/lint-staged) explain how to do this pretty well. 

One thing to note is that we'll need `prettier` in `devDependencies` for the `mrm` command to work.

**Comment by DavidRecheni** [comment]
Hey, can I take this task?
