### ISSUE TITLE
README.md needs to be updated and react-query error

### ISSUE THREAD

**Issue by georgemac510** [Developer-DAO/school-of-code#31]
The README.md should probably include:

**Prerequisites:**

          node --version 16.x

Refer to the `node` and `npm` installation with `nvm` guide in Lesson 2. A link to the guide can be found here:
https://www.notion.so/How-to-install-node-js-and-npm-67b2ab1f76f148f49f547b9156aeaf28

**Clone and `cd` into the repo:** 

           git clone https://github.com/Developer-DAO/school-of-code.git
           cd school-of-code/

**Installation and run:**

           yarn install 

           yarn dev

This will create a local instance of the app running and can be viewed at `http://localhost:3000` in your browser.<br>
                                                                                                                                                                                 <br>

**Since this is a work in progress, your local version of the app can be updated with the following commands:**

Stop the app with:

           Ctrl + C

Use `git pull` for the most up-to-date version:

           git pull https://github.com/Developer-DAO/school-of-code.git

Reinstall with `yarn`:

           yarn install

Run the updated app:

           yarn dev

**Comment by briangershon** [comment]
Hey @georgemac510 

I just gave it a try -- I do see the error when doing `npm install` but don't see any errors when doing `yarn install`.

I'd propose we toss the NPM instructions -- mainly because we have a `yarn.lock` file. If we leave in `npm` instructions, at some point someone will create a `package-lock.json` and we'll have to lock files.

In other words, let's just use `yarn` for installing and `yarn dev` for running dev server.

Also, I'd recommend we just mention Node 16.x as dependency since it's the LTS version (and not mention v14)

**Comment by georgemac510** [comment]
Hey @briangershon

I made all of the suggested changes you mentioned above and used `yarn`. It resolved all issues. Very cool UI. Great to finally see it. I'll close #31 unless you think I should make some other changes.

**Comment by briangershon** [comment]
Thanks @georgemac510, that's great `yarn` resolving the issues!

Feel free to ping me on your PR if you want me to review README changes.

**Comment by georgemac510** [comment]
Will do. Thanks @briangershon

**Comment by georgemac510** [comment]
Hi @briangershon I think this may be finished unless you think I should add additional info.

**Comment by briangershon** [comment]
Thanks @georgemac510 -- just let me know when you open a PR with these changes in the README.

Github has a cool feature where in your PR description, you can type `Closes #31` so after PR is reviewed and merged, Github will automatically close that issue since everything is then complete.

**Comment by georgemac510** [comment]
Hey @briangershon Sorry for the noobish question, but do I need permission to start another branch for a pull request? I figured that I could start a branch since the README.md will need to be updated a few times before we're done. I don't think I have those permissions.

**Comment by briangershon** [comment]
Successfully merged,
