### ISSUE TITLE
Build "Getting Started" page

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/school-of-code#49]
## Development

- [x] Add new "Getting Started" page and route with "lessons" list on the bottom
- [x] Hook it up from "Getting Started" button on home page
- [x] Add "Getting Started" to top navigation
- [x] Move Feedback and link to lessons to the top, then ease into roadmap, etc.
- [x] How to get involved in the project - get people excited about writing content too

## Content

A great example of a Getting Started page is here: <https://www.30daysofweb3.xyz/curriculum/1-getting-started/0-overview>

- [x] About project / goals of project
- [X] Where to give feedback (e.g. point to our Github Issues and our new bug report form) -- See also #50 
- [X] Project Roadmap

As our content and lessons grow, we'll split these items out to separate pages.

**Comment by briangershon** [comment]
Assigning to @ropats16 to kick things off, and then potentially pull in others to help fill things out.

**Comment by briangershon** [comment]
Thanks @ropats16 for adding the initial page, route and navigation. I marked those completed.

I also pulled you off of this issue to open it up for additional contributors to work on the content piece.

**Comment by elPiablo** [comment]
superstars!!
