### ISSUE TITLE
Connect Wallet Button in Header

### ISSUE THREAD

**Issue by ropats16** [Developer-DAO/school-of-code#5]
Use the [Rainbow Kit]{https://www.rainbowkit.com/docs/introduction} to create Connect Wallet Button.

Use the following figma as reference for the Connect Wallet Button placement and Styling:
https://www.figma.com/file/hSfH9Bl6JMJHsYaZ3FE6S7/School?node-id=730%3A44674

**Comment by casasmartinignacio** [comment]
Hi. I'd like to take this issue
