### ISSUE TITLE
Fix mobile responsive issues on getting-started

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/school-of-code#53]
Issue: on mobile (iPhone 13) the text on the lessons icons is overflowing on the getting-started lessons components 
![0901956A-9806-4B84-B95D-064F60416B74](https://user-images.githubusercontent.com/45179070/183309920-2f9b52dc-91c2-4487-a3c1-b04dfb7c391b.png)

**Comment by briangershon** [comment]
Related to PR #52

**Comment by PBillingsby** [comment]
Related to PR #59

**Comment by briangershon** [comment]
PR #59 merged and resolves this issue.
