### ISSUE TITLE
Text and Get Started Button in Hero

### ISSUE THREAD

**Issue by ropats16** [Developer-DAO/school-of-code#6]
Use the following figma as reference for the Hero Text placement and Styling:
https://www.figma.com/file/hSfH9Bl6JMJHsYaZ3FE6S7/School?node-id=730%3A44674

There are three sub elements:
- heading
- paragraph
- Get Started Button

Use [Chakra UI](https://chakra-ui.com/) library.

Ensure Elements are responsive to be readable on devices of all various sizes as shown in figma.

**Comment by PBillingsby** [comment]
This has been resolved by #16
