### ISSUE TITLE
Add cookie consent banner

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/school-of-code#67]
With FullStory being initialized on load and tracking, we need to add a cookie consent banner that gives the User the ability to opt out.

**Comment by briangershon** [comment]
Good catch!

Maybe we can use a free third-party service like https://termly.io -- I've used OneTrust for corporate compliance, but they don't have a free version for small sites.

**Comment by PBillingsby** [comment]
Will definitely look into termly. 

For p3rks I used `react-cookie-consent` package and just wrapped the analytics initializer in a conditional based on that response. Was quite simple

**Comment by briangershon** [comment]
Simple always sounds good to me! `react-cookie-consent` seems like it would do the trick.

I also poked around and found the data collection on/off methods for Fullstory API: https://help.fullstory.com/hc/en-us/articles/360020623314-FS-shutdown-and-FS-restart

**Comment by briangershon** [comment]
Completed in PR #90
