### ISSUE TITLE
Image for Hero

### ISSUE THREAD

**Issue by ropats16** [Developer-DAO/school-of-code#7]
Use the following figma as reference for Hero Image placement and Styling:
https://www.figma.com/file/hSfH9Bl6JMJHsYaZ3FE6S7/School?node-id=730%3A44674

Get Design from Erik and re-create as SVG or CSS Property to ensure responsiveness to be readable on devices of all sizes as seen is figma.

**Comment by PBillingsby** [comment]
This has been resolved by #16
