### ISSUE TITLE
Add navigation between lessons

### ISSUE THREAD

**Issue by PBillingsby** [Developer-DAO/school-of-code#71]
Currently there is no way to navigate between lessons from each lesson page.

This issue is for adding forward and back navigation icons.

**Comment by briangershon** [comment]
We don't have any way to formally complete a Lesson or Track, so maybe last lesson in the Track says "Congratulations for completing the track".

We have one track atm, and it currently has two lessons, but a third is coming, and we'll work on 4 and 5 for MVP.

Implementation-wise, maybe Next.js static route approach (1.mdx, 2.mdx) needs to be converted into dynamic route approach?
