### ISSUE TITLE
Content can break mobile layout

### ISSUE THREAD

**Issue by briangershon** [Developer-DAO/school-of-code#81]
## Issue

I noticed Lesson 1, as well as Getting Started have issues where content breaks the design on mobile.

## Some Possible Solution

- CSS to ensure wrapping
- shrinking content (albeit it will be easy for bug to come back)

## More Details

![IMG_5470](https://user-images.githubusercontent.com/139330/186983237-8f57c19e-ba5a-4221-a65d-afb1b54c9970.PNG)

![IMG_5469](https://user-images.githubusercontent.com/139330/186983242-42dd5272-01e6-48e7-981b-3c5f0408895d.PNG)

**Comment by exas-3** [comment]
Related to issue #53

**Comment by briangershon** [comment]
Fixed in PR https://github.com/Developer-DAO/school-of-code/pull/82
